- name: ensure nginx is at the latest version
  apt: 
    name: nginx 
    state: latest

  become: yes
  become_method: sudo
- name: Copy gunicorn service
  template:
    src: gunicorn-service
    dest: "/etc/systemd/system/{{ app_name }}.service"

- name: Start gunicorn app service on boot
  systemd: 
    name: "{{ app_name }}"
    daemon_reload: yes 
    state: restarted
    enabled: yes

- name: Copy nginx site config file
  template:
    src: nginx-config
    dest: "/etc/nginx/sites-available/{{ app_name }}"

- name: Remove default nginx site config
  file:  
    path: /etc/nginx/sites-enabled/default 
    state: absent

- name: Enable nginx site
  file:
    src: "/etc/nginx/sites-available/{{ app_name }}"
    dest: /etc/nginx/sites-enabled/default
    state: link
    force: yes

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
